context("Model wrappers")
library(finalfit)
test_example("/home/eharrison/finalfit/man/glmuni.Rd")
test_example("/home/eharrison/finalfit/man/glmmulti.Rd")
test_example("/home/eharrison/finalfit/man/glmmixed.Rd")
test_example("/home/eharrison/finalfit/man/glmmulti_boot.Rd")

context("Model wrappers 2")
library(finalfit)
test_example("/home/eharrison/finalfit/man/lmuni.Rd")
test_example("/home/eharrison/finalfit/man/lmmulti.Rd")
test_example("/home/eharrison/finalfit/man/lmmixed.Rd")

context("Model wrappers 3")
library(finalfit)
test_example("/home/eharrison/finalfit/man/coxphuni.Rd")
test_example("/home/eharrison/finalfit/man/coxphmulti.Rd")

context("Boot")
library(finalfit)
test_example("/home/eharrison/finalfit/man/boot_compare.Rd")
test_example("/home/eharrison/finalfit/man/boot_predict.Rd")

context("Helpers")
library(finalfit)
test_example("/home/eharrison/finalfit/man/ff_glimpse.Rd")
test_example("/home/eharrison/finalfit/man/ff_newdata.Rd")
test_example("/home/eharrison/finalfit/man/ff_merge.Rd")

context("Missing")
library(finalfit)
test_example("/home/eharrison/finalfit/man/missing_compare.Rd")
test_example("/home/eharrison/finalfit/man/missing_pairs.Rd")
test_example("/home/eharrison/finalfit/man/missing_plot.Rd")
test_example("/home/eharrison/finalfit/man/missing_pattern.Rd")

context("Plots")
library(finalfit)
test_example("/home/eharrison/finalfit/man/hr_plot.Rd")
test_example("/home/eharrison/finalfit/man/or_plot.Rd")
#test_example("/home/eharrison/finalfit/man/surv_plot.Rd")

context("All in one")
library(finalfit)
test_example("/home/eharrison/finalfit/man/finalfit.Rd")
test_example("/home/eharrison/finalfit/man/summary_factorlist.Rd")
test_example("/home/eharrison/finalfit/man/fit2df.Rd")
