context("Model wrappers")
library(finalfit)
test_example("../../man/glmuni.Rd")
test_example("../../man/glmmulti.Rd")
test_example("../../man/glmmixed.Rd")
test_example("../../man/glmmulti_boot.Rd")

context("Model wrappers 2")
library(finalfit)
test_example("../../man/lmuni.Rd")
test_example("../../man/lmmulti.Rd")
test_example("../../man/lmmixed.Rd")

context("Model wrappers 3")
library(finalfit)
test_example("../../man/coxphuni.Rd")
test_example("../../man/coxphmulti.Rd")

context("Boot")
library(finalfit)
test_example("../../man/boot_compare.Rd")
test_example("../../man/boot_predict.Rd")

context("Helpers")
library(finalfit)
test_example("../../man/ff_glimpse.Rd")
test_example("../../man/ff_newdata.Rd")
test_example("../../man/ff_merge.Rd")

context("Missing")
library(finalfit)
test_example("../../man/missing_compare.Rd")
test_example("../../man/missing_pairs.Rd")
test_example("../../man/missing_plot.Rd")
test_example("../../man/missing_pattern.Rd")

context("Plots")
library(finalfit)
test_example("../../man/hr_plot.Rd")
test_example("../../man/or_plot.Rd")
#test_example("../../man/surv_plot.Rd")

context("All in one")
library(finalfit)
test_example("../../man/finalfit.Rd")
test_example("../../man/summary_factorlist.Rd")
test_example("../../man/fit2df.Rd")
